### ISSUE TITLE
Great library, but size is too big

### ISSUE THREAD

**Issue by itsramiel** [nghinv-software/react-native-search-bar#2]
Hey. I just want to thank you for this really smooth component. I have been searching for a searchbox for a while, and I was going to write my own reanimated searchbox until I stumbled upon this. REALLY GREAT, BUT...

I am really have no experience building out packages, but when I installed the packaged and used it, I saw that the package size is way too big. Here is a picture from an extension I have from vs code:
![Capture](https://user-images.githubusercontent.com/80689446/147348176-0f101ecc-3b56-4a21-921a-4880f5406f0e.PNG)

I have no idea why it is taking so much space, so I really just copied the index.tsx into a local component. I really dont want to do that, and I want to use your library as a dependency, but I hope you can fix the size issue.

As I see i copied your src folder and the component works, but the lib folder is really heavy about 58kb which does not seem to affect the working of library. As I said before I have no idea how packages work, but I just wanted to let you know that because this component really helped, and you should put this in reactnative.directory after fixing the size issue

**Comment by Nghi-NV** [comment]
Thank you for your response. I think this problem because my lib required react-native-vector-icons/dist/Ionicons
